# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.prod.com:
  peer0.org1.prod.com:
  peer1.org1.prod.com:
  peer0.org2.prod.com:
  peer1.org2.prod.com:
  ca.org1.prod.com:
  ca.org2.prod.com:

networks:
  prod:

services:
  ca.org1.prod.com:
    image: hyperledger/fabric-ca:x86_64-1.1.0-preview
    environment:
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.prod.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.prod.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.prod.com_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org1.prod.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.prod.com
    networks:
      - prod

  ca.org2.prod.com:
    image: hyperledger/fabric-ca:x86_64-1.1.0-preview
    environment:
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.prod.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.prod.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.prod.com_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org2.prod.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org2.prod.com
    networks:
      - prod
  
  orderer.prod.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.prod.com
    container_name: orderer.prod.com
    networks:
      - prod

  orderer2.prod.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer2.prod.com
    container_name: orderer2.prod.com
    networks:
      - prod
  
  orderer3.prod.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer3.prod.com
    container_name: orderer3.prod.com
    networks:
      - prod
    
  orderer4.prod.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer4.prod.com
    container_name: orderer4.prod.com
    networks:
      - prod

  orderer5.prod.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer5.prod.com
    container_name: orderer5.prod.com
    networks:
      - prod

  peer0.org1.prod.com:
    container_name: peer0.org1.prod.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.prod.com
    networks:
      - prod

  peer1.org1.prod.com:
    container_name: peer1.org1.prod.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.prod.com
    networks:
      - prod

  peer0.org2.prod.com:
    container_name: peer0.org2.prod.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.prod.com
    networks:
      - prod

  peer1.org2.prod.com:
    container_name: peer1.org2.prod.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.prod.com
    networks:
      - prod

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.prod.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.prod.com/peers/peer0.org1.prod.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.prod.com/peers/peer0.org1.prod.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.prod.com/peers/peer0.org1.prod.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.prod.com/users/Admin@org1.prod.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.prod.com
      - orderer2.prod.com
      - orderer3.prod.com
      - orderer4.prod.com
      - orderer5.prod.com
      - peer0.org1.prod.com
      - peer1.org1.prod.com
      - peer0.org2.prod.com
      - peer1.org2.prod.com
      - ca.org1.prod.com
      - ca.org2.prod.com
    networks:
      - prod